trigger:
- main

pool:
  name: Default

steps:

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.x'

- script: dotnet restore WebApplication1/WebApplication1.csproj
  displayName: Restore dependencies

- script: dotnet build WebApplication1/WebApplication1.csproj --configuration Release
  displayName: Build project

- script: dotnet publish WebApplication1/WebApplication1.csproj --configuration Release --output $(Build.ArtifactStagingDirectory)
  displayName: Publish project

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'

- task: AzureWebApp@1
  displayName: Deploy to Azure Web App
  inputs:
    azureSubscription: 'Azure-Service-Connection'
    appName: 'sampleApp'
    package: '$(Build.ArtifactStagingDirectory)'
